font_family      JetBrainsMono Nerd Font Mono
bold_font        JetBrainsMono Nerd Font Mono Extra Bold
bold_italic_font JetBrainsMono Nerd Font Mono Extra Bold Italic
font_size        12.0
italic_font      auto


cursor_trail 1

background_opacity 1.0
confirm_os_window_close 0

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no
hide_window_decorations yes

window_padding_width 4

disable_ligatures always
include ~/.config/kitty/kitty-colors.conf
background_opacity 0.6

