general {
    disable_loading_bar = true
    hide_cursor = true
    grace = 2
}

background {
    monitor =
    path = screenshot

    blur_passes = 1
    blur_size = 8

    noise = 0.015

    brightness = 0.9
    contrast = 1.05

    vibrancy = 0.18
    vibrancy_darkness = 0.2
}

shape {
    monitor =

    size = 420, 300
    position = 0, 10

    color = rgba(16, 18, 23, 0.78)

    rounding = 24

    border_size = 1
    border_color = rgba(255,255,255,0.08)

    halign = center
    valign = center
}

label {
    monitor =

    text = cmd[update:1000] echo "$(date '+%H:%M')"

    color = rgba(245,247,250,1.0)

    font_size = 60
    font_family = JetBrainsMono Nerd Font Bold

    position = 0, 53

    halign = center
    valign = center
}

label {
    monitor =

    text = $USER

    color = rgba(183,192,204,1.0)

    font_size = 12
    font_family = JetBrainsMono Nerd Font

    position = 0, 110

    halign = center
    valign = center
}

image {
    monitor =

    path = ~/.face

    size = 82

    rounding = -1
    border_size = 2
    border_color = rgba(255,255,255,0.08)

    position = 0, 168

    halign = center
    valign = center
}

input-field {
    monitor =

    size = 320, 54
    position = 0, -30

    outline_thickness = 0

    dots_size = 0.22
    dots_spacing = 0.5

    dots_center = true

    outer_color = rgba(0,0,0,0)
    inner_color = rgba(255,255,255,0.05)

    font_color = rgb(245,247,250)

    fade_on_empty = false

    placeholder_text = <span foreground="##b7c0cc">Password...</span>

    rounding = 16

    check_color = rgba(255,255,255,0.1)
    fail_color = rgba(255,80,80,0.2)

    halign = center
    valign = center
}

label {
    monitor =

    text = Locked

    color = rgba(183,192,204,0.55)

    font_size = 14
    font_family = JetBrainsMono Nerd Font

    position = 0, -95

    halign = center
    valign = center
}

animations {
    enabled = true
    bezier = easeOut, 0.16, 1, 0.3, 1
    animation = fadeIn, 1, 3, easeOut
    animation = fadeOut, 1, 3, easeOut
    animation = inputFieldColors, 1, 3, easeOut
    animation = labelFadeIn, 1, 4, easeOut
    animation = imageFadeIn, 1, 4, easeOut
}