windowrule = match:class ^(pavucontrol)$, float on
windowrule = match:class ^(blueman-manager)$, float on
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(dolphin)$, float on, center on, size 900 600
windowrule = match:class ^(scratchpad-kitty)$, float on, size 900 550, center on
