#!/usr/bin/env python3
import sys
import os

rules_path = os.path.expanduser("~/.config/hypr/rules.conf")

# Input: passed as command line arguments, each arg is "rule\tfilter"
entries = []
for arg in sys.argv[1:]:
    if "\t" not in arg:
        continue
    parts = arg.split("\t", 1)
    rule, fltr = parts[0].strip(), parts[1].strip()
    if rule and fltr:
        entries.append(f"windowrule = match:{fltr}, {rule}")

with open(rules_path, "w") as f:
    f.write("# Auto-generated by RulesEditor\n")
    for entry in entries:
        f.write(entry + "\n")

print("ok")